services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL
      - REDIS_URL
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    restart: unless-stopped

  worker:
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL
      - REDIS_URL
    command: celery -A app.tasks:celery worker --loglevel=info
    restart: unless-stopped