"""document logs mode

Revision ID: 05d83dbf6bed
Revises: aa828b1c2702
Create Date: 2025-09-23 20:05:52.957832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d83dbf6bed'
down_revision: Union[str, Sequence[str], None] = 'aa828b1c2702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_logs', sa.Column('logs', sa.JSON(), nullable=False))
    op.drop_column('document_logs', 'chunk_processed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_logs', sa.Column('chunk_processed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('document_logs', 'logs')
    # ### end Alembic commands ###
