"""Staging migration

Revision ID: 7d18b1faae2f
Revises: b248b01e034d
Create Date: 2025-09-16 15:43:41.175063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d18b1faae2f'
down_revision: Union[str, Sequence[str], None] = 'b248b01e034d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('latest_revision_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_document_latest_revision_id'), 'document', ['latest_revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_latest_revision_id'), table_name='document')
    op.drop_column('document', 'latest_revision_id')
    # ### end Alembic commands ###
