"""Staging migration

Revision ID: 80c0cf08d87a
Revises: 3179b5c5a9b4
Create Date: 2025-08-03 21:58:48.485374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c0cf08d87a'
down_revision: Union[str, Sequence[str], None] = '3179b5c5a9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_id'), 'department', ['id'], unique=False)
    op.create_index(op.f('ix_department_is_active'), 'department', ['is_active'], unique=False)
    op.create_index(op.f('ix_department_is_global'), 'department', ['is_global'], unique=False)
    op.create_index(op.f('ix_department_name'), 'department', ['name'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_is_active'), 'category', ['is_active'], unique=False)
    op.create_index(op.f('ix_category_is_global'), 'category', ['is_global'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_table('document_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_type_id'), 'document_type', ['id'], unique=False)
    op.create_index(op.f('ix_document_type_is_active'), 'document_type', ['is_active'], unique=False)
    op.create_index(op.f('ix_document_type_is_global'), 'document_type', ['is_global'], unique=False)
    op.create_index(op.f('ix_document_type_name'), 'document_type', ['name'], unique=False)
    op.create_table('folder',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folder_id'), 'folder', ['id'], unique=False)
    op.create_index(op.f('ix_folder_is_active'), 'folder', ['is_active'], unique=False)
    op.create_index(op.f('ix_folder_name'), 'folder', ['name'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_uploaded', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_category_id'), 'document', ['category_id'], unique=False)
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_index(op.f('ix_document_is_active'), 'document', ['is_active'], unique=False)
    op.create_index(op.f('ix_document_is_deleted'), 'document', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_document_is_uploaded'), 'document', ['is_uploaded'], unique=False)
    op.create_index(op.f('ix_document_name'), 'document', ['name'], unique=False)
    op.create_index(op.f('ix_document_status'), 'document', ['status'], unique=False)
    op.create_table('prompt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_category_id'), 'prompt', ['category_id'], unique=False)
    op.create_index(op.f('ix_prompt_document_type_id'), 'prompt', ['document_type_id'], unique=False)
    op.create_index(op.f('ix_prompt_id'), 'prompt', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_is_active'), 'prompt', ['is_active'], unique=False)
    op.create_index(op.f('ix_prompt_is_archived'), 'prompt', ['is_archived'], unique=False)
    op.create_index(op.f('ix_prompt_name'), 'prompt', ['name'], unique=False)
    op.create_index(op.f('ix_prompt_published'), 'prompt', ['published'], unique=False)
    op.create_table('document_accessible_member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_level', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_accessible_member_id'), 'document_accessible_member', ['id'], unique=False)
    op.create_index(op.f('ix_document_accessible_member_is_active'), 'document_accessible_member', ['is_active'], unique=False)
    op.create_index(op.f('ix_document_accessible_member_permission_level'), 'document_accessible_member', ['permission_level'], unique=False)
    op.create_table('document_revision_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('prompt_used_id', sa.UUID(), nullable=True),
    sa.Column('previous_content', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['prompt_used_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_revision_history_id'), 'document_revision_history', ['id'], unique=False)
    op.create_index(op.f('ix_document_revision_history_is_active'), 'document_revision_history', ['is_active'], unique=False)
    op.add_column('user', sa.Column('department_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('invited_by', sa.UUID(), nullable=True))
    op.add_column('user', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('invited_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_department_id'), 'user', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'user', 'department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'user', 'user', ['invited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_department_id'), table_name='user')
    op.drop_column('user', 'invited_at')
    op.drop_column('user', 'registered_at')
    op.drop_column('user', 'invited_by')
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'department_id')
    op.drop_index(op.f('ix_document_revision_history_is_active'), table_name='document_revision_history')
    op.drop_index(op.f('ix_document_revision_history_id'), table_name='document_revision_history')
    op.drop_table('document_revision_history')
    op.drop_index(op.f('ix_document_accessible_member_permission_level'), table_name='document_accessible_member')
    op.drop_index(op.f('ix_document_accessible_member_is_active'), table_name='document_accessible_member')
    op.drop_index(op.f('ix_document_accessible_member_id'), table_name='document_accessible_member')
    op.drop_table('document_accessible_member')
    op.drop_index(op.f('ix_prompt_published'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_name'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_is_archived'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_is_active'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_id'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_document_type_id'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_category_id'), table_name='prompt')
    op.drop_table('prompt')
    op.drop_index(op.f('ix_document_status'), table_name='document')
    op.drop_index(op.f('ix_document_name'), table_name='document')
    op.drop_index(op.f('ix_document_is_uploaded'), table_name='document')
    op.drop_index(op.f('ix_document_is_deleted'), table_name='document')
    op.drop_index(op.f('ix_document_is_active'), table_name='document')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_index(op.f('ix_document_category_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_folder_name'), table_name='folder')
    op.drop_index(op.f('ix_folder_is_active'), table_name='folder')
    op.drop_index(op.f('ix_folder_id'), table_name='folder')
    op.drop_table('folder')
    op.drop_index(op.f('ix_document_type_name'), table_name='document_type')
    op.drop_index(op.f('ix_document_type_is_global'), table_name='document_type')
    op.drop_index(op.f('ix_document_type_is_active'), table_name='document_type')
    op.drop_index(op.f('ix_document_type_id'), table_name='document_type')
    op.drop_table('document_type')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_is_global'), table_name='category')
    op.drop_index(op.f('ix_category_is_active'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_department_name'), table_name='department')
    op.drop_index(op.f('ix_department_is_global'), table_name='department')
    op.drop_index(op.f('ix_department_is_active'), table_name='department')
    op.drop_index(op.f('ix_department_id'), table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
