"""Staging migration

Revision ID: 8ce770a1924b
Revises: 80c0cf08d87a
Create Date: 2025-08-04 07:49:25.421156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce770a1924b'
down_revision: Union[str, Sequence[str], None] = '80c0cf08d87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_user_department_id'), table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_department_id'), 'user', ['department_id'], unique=False)
    op.alter_column('user', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('document', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
