"""user model to Users

Revision ID: 96ea19301e3f
Revises: 680053e6778d
Create Date: 2025-08-04 14:11:49.423354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ea19301e3f'
down_revision: Union[str, Sequence[str], None] = '680053e6778d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='users')
    op.drop_index(op.f('ix_user_first_name'), table_name='users')
    op.drop_index(op.f('ix_user_id'), table_name='users')
    op.drop_index(op.f('ix_user_is_active'), table_name='users')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_user_last_name'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_user_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_user_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
