"""document logs mode

Revision ID: aa828b1c2702
Revises: 7d18b1faae2f
Create Date: 2025-09-22 19:56:33.109659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa828b1c2702'
down_revision: Union[str, Sequence[str], None] = '7d18b1faae2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('chunk_processed', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_logs_id'), 'document_logs', ['id'], unique=False)
    op.create_index(op.f('ix_document_logs_is_active'), 'document_logs', ['is_active'], unique=False)
    op.create_index(op.f('ix_document_logs_revision_id'), 'document_logs', ['revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_logs_revision_id'), table_name='document_logs')
    op.drop_index(op.f('ix_document_logs_is_active'), table_name='document_logs')
    op.drop_index(op.f('ix_document_logs_id'), table_name='document_logs')
    op.drop_table('document_logs')
    # ### end Alembic commands ###
