"""doc status columns changed  str to int

Revision ID: b248b01e034d
Revises: e499dab33275
Create Date: 2025-08-06 02:01:08.302970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b248b01e034d'
down_revision: Union[str, Sequence[str], None] = 'e499dab33275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('status', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_document_status'), 'document', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_status'), table_name='document')
    op.drop_column('document', 'status')
    # ### end Alembic commands ###
