"""doc status columns changed  str to int

Revision ID: e499dab33275
Revises: 4c61420d6be4
Create Date: 2025-08-06 01:59:19.236666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e499dab33275'
down_revision: Union[str, Sequence[str], None] = '4c61420d6be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_status'), table_name='document')
    op.drop_column('document', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_document_status'), 'document', ['status'], unique=False)
    # ### end Alembic commands ###
